# Start with the official NGINX image
FROM nginx:latest

# Remove the default configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy your custom nginx.conf to the proper location
COPY nginx.conf /etc/nginx/nginx.conf
